-- ==========================================================================
-- Content Calendar: proactive daily content planning
--
-- Each row is a planned content slot — a topic/pillar/platform assignment
-- for a specific date and time window, generated by the planning job and
-- informed by strategy insights, analytics, and trend signals.
--
-- Slots start as 'planned', become 'generated' when content is created
-- from them, and 'posted' when published.
-- ==========================================================================

create table if not exists content_calendar (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) not null,

  -- When and where
  planned_date date not null,
  time_slot text not null check (time_slot in ('morning', 'midday', 'evening', 'late_night')),
  platform text not null default 'threads',

  -- What to create
  pillar text not null,                   -- 'running', 'building', 'nyc', 'fitness', 'travel'
  topic text not null,                    -- specific content idea
  format text not null default 'single_post', -- 'single_post', 'thread', 'carousel', 'reel'
  rationale text,                         -- why this topic, why this time
  trend_relevance decimal default 0,      -- 0-1, how tied to current trends

  -- Lifecycle
  status text not null default 'planned' check (status in ('planned', 'generating', 'generated', 'posted', 'skipped')),
  content_queue_id uuid references content_queue(id), -- link to generated content
  skipped_reason text,                    -- why a slot was skipped

  -- Metadata
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One slot per date/time/platform combination
create unique index if not exists idx_content_calendar_slot
  on content_calendar (user_id, planned_date, time_slot, platform);

create index if not exists idx_content_calendar_date
  on content_calendar (user_id, planned_date, status);

alter table content_calendar enable row level security;
create policy "Users manage own content calendar"
  on content_calendar for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
